name: Bug report
description: Create a report to help us improve SQLPro apps
title: "[Bug]: "
labels: ['type:bug-suspected']
assignees: hankinsoft

body:
  - type: textarea
    id: bug
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      value: |
        **Describe the bug**
        A clear and concise description of what the bug is.

        **To Reproduce**
        Steps to reproduce the behavior:
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error

        **Expected behavior**
        A clear and concise description of what you expected to happen.

        **Screenshots**
        If applicable, add screenshots to help explain your problem.

        **Additional details**
        Enter any additional details we should know about.
    validations:
      minLength: 30
      required: true

  - type: dropdown
    id: product
    attributes:
      label: Product
      description: Which product are you using?
      options:
        - Choose one
        - SQLPro Studio
        - SQLPro for MySQL
        - SQLPro for MSSQL
        - SQLPro for Oracle
        - SQLPro for SQLite
        - SQLPro for Postgres
        - SQLPro for Snowflake
    validations:
      required: true

  - type: input
    id: app-version
    attributes:
      label: App version
      description: Paste the exact version/build number (e.g. 2025.x).
    validations:
      required: true
      pattern:
        value: '^\d{4}\.\d+$'
        message: "Use the format 4-digit year, a dot, then the build number (e.g. 2025.1)."

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: What platform are you having the issue on?
options:
  - label: "— Choose one —"
    value: ""          # empty → keeps form invalid while required: true
  - label: "SQLPro Studio"
    value: "SQLPro Studio"
  - label: "SQLPro for MySQL"
    value: "SQLPro for MySQL"
  - label: "SQLPro for MSSQL"
    value: "SQLPro for MSSQL"
  - label: "SQLPro for Oracle"
    value: "SQLPro for Oracle"
  - label: "SQLPro for SQLite"
    value: "SQLPro for SQLite"
  - label: "SQLPro for Postgres"
    value: "SQLPro for Postgres"
  - label: "SQLPro for Snowflake"
    value: "SQLPro for Snowflake"
    validations:
      required: true

  - type: dropdown
    id: install-source
    attributes:
      label: Installation source
      description: Where did you install the app from?
      options:
        - Choose one
        - App Store
        - Setapp
        - Website download
        - TestFlight
        - Other
    validations:
      required: true
