name: Bug report
description: Create a report to help us improve SQLPro apps
title: ""
labels: ['type:bug-suspected']
assignees: hankinsoft

body:
  - type: textarea
    id: bug
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      value: |
        **Describe the bug**
        A clear and concise description of what the bug is.

        **To Reproduce**
        Steps to reproduce the behavior:
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error

        **Expected behavior**
        A clear and concise description of what you expected to happen.

        **Screenshots**
        If applicable, add screenshots to help explain your problem.
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Product and version details
      value: |
        - SQLPro Product: Ex: SQLPro Studio, SQLPro for SQLite, SQLPro for MySQL, etc).
        - SQLPro app version: Ex: 2025.14
        - Target database server: Ex: MySQL
    validations:
      required: true

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: What platform are you having the issue on?
      options:
        - macOS
        - iPhone
        - iPad
        - Windows
    validations:
      required: true

  - type: dropdown
    id: install-source
    attributes:
      label: Installation source
      description: Where did you install the app from?
      options:
        - App Store
        - Setapp
        - Website download
        - TestFlight
        - Other
    validations:
      required: true

  - type: textarea
    id: extra
    attributes:
      label: Additional context
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        _Issues without complete environment details will be closed automatically._
