# .github/ISSUE_TEMPLATE/bug_report.yml
name: Bug report
description: Create a report to help us improve
title: ''
labels: ''
assignees: hankinsoft
body:
  - type: markdown
    attributes:
      value: |
        ## Thanks for taking the time to file a bug!
        Please complete **all** fields. Issues submitted without the required information will not be accepted.
  - type: textarea
    id: bug
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: A step-by-step list so we can see the issue too.
      value: |
        1. …
        2. …
        3. …
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behaviour
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment details
      value: |
        - Device:
        - OS:
        - SQLPro app version:
        - Installation source:
        - Target database server:
    validations:
      required: true
  - type: textarea
    id: extra
    attributes:
      label: Additional context

